import type { CSSProperties } from "react";

/** Shared between the login and registration screens so the two cannot drift. */
export const authPageStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#f8fafc",
    fontFamily: "system-ui, -apple-system, Segoe UI, Arial, sans-serif",
    color: "#0f172a",
  },
  card: {
    width: 340,
    padding: 24,
    background: "#fff",
    borderRadius: 8,
    boxShadow: "0 20px 40px rgba(15, 23, 42, 0.12)",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  title: { margin: 0, fontSize: 18, fontWeight: 600 },
  subtitle: { margin: "0 0 8px", fontSize: 12, color: "#64748b" },
  label: { display: "flex", flexDirection: "column", gap: 4, fontSize: 13 },
  input: {
    padding: "8px 10px",
    border: "1px solid #cbd5e1",
    borderRadius: 6,
    fontSize: 14,
    fontFamily: "inherit",
  },
  error: {
    margin: 0,
    padding: "8px 10px",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderRadius: 6,
    color: "#b91c1c",
    fontSize: 13,
  },
  hint: { margin: 0, fontSize: 12, color: "#64748b" },
  primaryButton: {
    marginTop: 4,
    padding: "9px 12px",
    background: "#0f172a",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    fontSize: 14,
    fontFamily: "inherit",
    cursor: "pointer",
  },
  linkButton: {
    background: "none",
    border: "none",
    color: "#1d4ed8",
    fontSize: 13,
    fontFamily: "inherit",
    cursor: "pointer",
    padding: 0,
  },
};
